// This file was generated by /var/folders/pc/l_kt_x3n3bqg49zc1c9cly8c0000gn/T/go-build137337949/command-line-arguments/_obj/exe/setup, using the container typewriter

package main

// The primary type that represents a set
type ThingSet map[Thing]struct{}

// Creates and returns a reference to an empty set.
func NewThingSet() ThingSet {
	return make(ThingSet)
}

// Creates and returns a reference to a set from an existing slice
func NewThingSetFromSlice(s []Thing) ThingSet {
	a := NewThingSet()
	for _, item := range s {
		a.Add(item)
	}
	return a
}

// Adds an item to the current set if it doesn't already exist in the set.
func (set ThingSet) Add(i Thing) bool {
	_, found := set[i]
	set[i] = struct{}{}
	return !found //False if it existed already
}

// Determines if a given item is already in the set.
func (set ThingSet) Contains(i Thing) bool {
	_, found := set[i]
	return found
}

// Determines if the given items are all in the set
func (set ThingSet) ContainsAll(i ...Thing) bool {
	allSet := NewThingSetFromSlice(i)
	if allSet.IsSubset(set) {
		return true
	}
	return false
}

// Determines if every item in the other set is in this set.
func (set ThingSet) IsSubset(other ThingSet) bool {
	for elem := range set {
		if !other.Contains(elem) {
			return false
		}
	}
	return true
}

// Determines if every item of this set is in the other set.
func (set ThingSet) IsSuperset(other ThingSet) bool {
	return other.IsSubset(set)
}

// Returns a new set with all items in both sets.
func (set ThingSet) Union(other ThingSet) ThingSet {
	unionedSet := NewThingSet()

	for elem := range set {
		unionedSet.Add(elem)
	}
	for elem := range other {
		unionedSet.Add(elem)
	}
	return unionedSet
}

// Returns a new set with items that exist only in both sets.
func (set ThingSet) Intersect(other ThingSet) ThingSet {
	intersection := NewThingSet()
	// loop over smaller set
	if set.Cardinality() < other.Cardinality() {
		for elem := range set {
			if other.Contains(elem) {
				intersection.Add(elem)
			}
		}
	} else {
		for elem := range other {
			if set.Contains(elem) {
				intersection.Add(elem)
			}
		}
	}
	return intersection
}

// Returns a new set with items in the current set but not in the other set
func (set ThingSet) Difference(other ThingSet) ThingSet {
	differencedSet := NewThingSet()
	for elem := range set {
		if !other.Contains(elem) {
			differencedSet.Add(elem)
		}
	}
	return differencedSet
}

// Returns a new set with items in the current set or the other set but not in both.
func (set ThingSet) SymmetricDifference(other ThingSet) ThingSet {
	aDiff := set.Difference(other)
	bDiff := other.Difference(set)
	return aDiff.Union(bDiff)
}

// Clears the entire set to be the empty set.
func (set *ThingSet) Clear() {
	*set = make(ThingSet)
}

// Allows the removal of a single item in the set.
func (set ThingSet) Remove(i Thing) {
	delete(set, i)
}

// Cardinality returns how many items are currently in the set.
func (set ThingSet) Cardinality() int {
	return len(set)
}

// Iter() returns a channel of type Thing that you can range over.
func (set ThingSet) Iter() <-chan Thing {
	ch := make(chan Thing)
	go func() {
		for elem := range set {
			ch <- elem
		}
		close(ch)
	}()

	return ch
}

// Equal determines if two sets are equal to each other.
// If they both are the same size and have the same items they are considered equal.
// Order of items is not relevent for sets to be equal.
func (set ThingSet) Equal(other ThingSet) bool {
	if set.Cardinality() != other.Cardinality() {
		return false
	}
	for elem := range set {
		if !other.Contains(elem) {
			return false
		}
	}
	return true
}

// Returns a clone of the set.
// Does NOT clone the underlying elements.
func (set ThingSet) Clone() ThingSet {
	clonedSet := NewThingSet()
	for elem := range set {
		clonedSet.Add(elem)
	}
	return clonedSet
}

// ThingElement is an element of a linked list.
type ThingElement struct {
	// Next and previous pointers in the doubly-linked list of elements.
	// To simplify the implementation, internally a list l is implemented
	// as a ring, such that &l.root is both the next element of the last
	// list element (l.Back()) and the previous element of the first list
	// element (l.Front()).
	next, prev *ThingElement

	// The list to which this element belongs.
	list *ThingList

	// The value stored with this element.
	Value Thing
}

// Next returns the next list element or nil.
func (e *ThingElement) Next() *ThingElement {
	if p := e.next; e.list != nil && p != &e.list.root {
		return p
	}
	return nil
}

// Prev returns the previous list element or nil.
func (e *ThingElement) Prev() *ThingElement {
	if p := e.prev; e.list != nil && p != &e.list.root {
		return p
	}
	return nil
}

// ThingList represents a doubly linked list.
// The zero value for ThingList is an empty list ready to use.
type ThingList struct {
	root ThingElement // sentinel list element, only &root, root.prev, and root.next are used
	len  int          // current list length excluding (this) sentinel element
}

// Init initializes or clears list l.
func (l *ThingList) Init() *ThingList {
	l.root.next = &l.root
	l.root.prev = &l.root
	l.len = 0
	return l
}

// New returns an initialized list.
func NewThingList() *ThingList { return new(ThingList).Init() }

// Len returns the number of elements of list l.
// The complexity is O(1).
func (l *ThingList) Len() int { return l.len }

// Front returns the first element of list l or nil
func (l *ThingList) Front() *ThingElement {
	if l.len == 0 {
		return nil
	}
	return l.root.next
}

// Back returns the last element of list l or nil.
func (l *ThingList) Back() *ThingElement {
	if l.len == 0 {
		return nil
	}
	return l.root.prev
}

// lazyInit lazily initializes a zero ThingList value.
func (l *ThingList) lazyInit() {
	if l.root.next == nil {
		l.Init()
	}
}

// insert inserts e after at, increments l.len, and returns e.
func (l *ThingList) insert(e, at *ThingElement) *ThingElement {
	n := at.next
	at.next = e
	e.prev = at
	e.next = n
	n.prev = e
	e.list = l
	l.len++
	return e
}

// insertValue is a convenience wrapper for insert(&ThingElement{Value: v}, at).
func (l *ThingList) insertValue(v Thing, at *ThingElement) *ThingElement {
	return l.insert(&ThingElement{Value: v}, at)
}

// remove removes e from its list, decrements l.len, and returns e.
func (l *ThingList) remove(e *ThingElement) *ThingElement {
	e.prev.next = e.next
	e.next.prev = e.prev
	e.next = nil // avoid memory leaks
	e.prev = nil // avoid memory leaks
	e.list = nil
	l.len--
	return e
}

// Remove removes e from l if e is an element of list l.
// It returns the element value e.Value.
func (l *ThingList) Remove(e *ThingElement) Thing {
	if e.list == l {
		// if e.list == l, l must have been initialized when e was inserted
		// in l or l == nil (e is a zero ThingElement) and l.remove will crash
		l.remove(e)
	}
	return e.Value
}

// PushFront inserts a new element e with value v at the front of list l and returns e.
func (l *ThingList) PushFront(v Thing) *ThingElement {
	l.lazyInit()
	return l.insertValue(v, &l.root)
}

// PushBack inserts a new element e with value v at the back of list l and returns e.
func (l *ThingList) PushBack(v Thing) *ThingElement {
	l.lazyInit()
	return l.insertValue(v, l.root.prev)
}

// InsertBefore inserts a new element e with value v immediately before mark and returns e.
// If mark is not an element of l, the list is not modified.
func (l *ThingList) InsertBefore(v Thing, mark *ThingElement) *ThingElement {
	if mark.list != l {
		return nil
	}
	// see comment in ThingList.Remove about initialization of l
	return l.insertValue(v, mark.prev)
}

// InsertAfter inserts a new element e with value v immediately after mark and returns e.
// If mark is not an element of l, the list is not modified.
func (l *ThingList) InsertAfter(v Thing, mark *ThingElement) *ThingElement {
	if mark.list != l {
		return nil
	}
	// see comment in ThingList.Remove about initialization of l
	return l.insertValue(v, mark)
}

// MoveToFront moves element e to the front of list l.
// If e is not an element of l, the list is not modified.
func (l *ThingList) MoveToFront(e *ThingElement) {
	if e.list != l || l.root.next == e {
		return
	}
	// see comment in ThingList.Remove about initialization of l
	l.insert(l.remove(e), &l.root)
}

// MoveToBack moves element e to the back of list l.
// If e is not an element of l, the list is not modified.
func (l *ThingList) MoveToBack(e *ThingElement) {
	if e.list != l || l.root.prev == e {
		return
	}
	// see comment in ThingList.Remove about initialization of l
	l.insert(l.remove(e), l.root.prev)
}

// MoveBefore moves element e to its new position before mark.
// If e is not an element of l, or e == mark, the list is not modified.
func (l *ThingList) MoveBefore(e, mark *ThingElement) {
	if e.list != l || e == mark {
		return
	}
	l.insert(l.remove(e), mark.prev)
}

// MoveAfter moves element e to its new position after mark.
// If e is not an element of l, or e == mark, the list is not modified.
func (l *ThingList) MoveAfter(e, mark *ThingElement) {
	if e.list != l || e == mark {
		return
	}
	l.insert(l.remove(e), mark)
}

// PushBackList inserts a copy of an other list at the back of list l.
// The lists l and other may be the same.
func (l *ThingList) PushBackList(other *ThingList) {
	l.lazyInit()
	for i, e := other.Len(), other.Front(); i > 0; i, e = i-1, e.Next() {
		l.insertValue(e.Value, l.root.prev)
	}
}

// PushFrontList inserts a copy of an other list at the front of list l.
// The lists l and other may be the same.
func (l *ThingList) PushFrontList(other *ThingList) {
	l.lazyInit()
	for i, e := other.Len(), other.Back(); i > 0; i, e = i-1, e.Prev() {
		l.insertValue(e.Value, &l.root)
	}
}

// A Ring is an element of a circular list, or ring.
// Rings do not have a beginning or end; a pointer to any ring element
// serves as reference to the entire ring. Empty rings are represented
// as nil Ring pointers. The zero value for a Ring is a one-element
// ring with a nil Value.
//
type ThingRing struct {
	next, prev *ThingRing
	Value      Thing // for use by client; untouched by this library
}

func (r *ThingRing) init() *ThingRing {
	r.next = r
	r.prev = r
	return r
}

// Next returns the next ring element. r must not be empty.
func (r *ThingRing) Next() *ThingRing {
	if r.next == nil {
		return r.init()
	}
	return r.next
}

// Prev returns the previous ring element. r must not be empty.
func (r *ThingRing) Prev() *ThingRing {
	if r.next == nil {
		return r.init()
	}
	return r.prev
}

// Move moves n % r.Len() elements backward (n < 0) or forward (n >= 0)
// in the ring and returns that ring element. r must not be empty.
//
func (r *ThingRing) Move(n int) *ThingRing {
	if r.next == nil {
		return r.init()
	}
	switch {
	case n < 0:
		for ; n < 0; n++ {
			r = r.prev
		}
	case n > 0:
		for ; n > 0; n-- {
			r = r.next
		}
	}
	return r
}

// New creates a ring of n elements.
func NewThingRing(n int) *ThingRing {
	if n <= 0 {
		return nil
	}
	r := new(ThingRing)
	p := r
	for i := 1; i < n; i++ {
		p.next = &ThingRing{prev: p}
		p = p.next
	}
	p.next = r
	r.prev = p
	return r
}

// Link connects ring r with ring s such that r.Next()
// becomes s and returns the original value for r.Next().
// r must not be empty.
//
// If r and s point to the same ring, linking
// them removes the elements between r and s from the ring.
// The removed elements form a subring and the result is a
// reference to that subring (if no elements were removed,
// the result is still the original value for r.Next(),
// and not nil).
//
// If r and s point to different rings, linking
// them creates a single ring with the elements of s inserted
// after r. The result points to the element following the
// last element of s after insertion.
//
func (r *ThingRing) Link(s *ThingRing) *ThingRing {
	n := r.Next()
	if s != nil {
		p := s.Prev()
		// Note: Cannot use multiple assignment because
		// evaluation order of LHS is not specified.
		r.next = s
		s.prev = r
		n.prev = p
		p.next = n
	}
	return n
}

// Unlink removes n % r.Len() elements from the ring r, starting
// at r.Next(). If n % r.Len() == 0, r remains unchanged.
// The result is the removed subring. r must not be empty.
//
func (r *ThingRing) Unlink(n int) *ThingRing {
	if n <= 0 {
		return nil
	}
	return r.Link(r.Move(n + 1))
}

// Len computes the number of elements in ring r.
// It executes in time proportional to the number of elements.
//
func (r *ThingRing) Len() int {
	n := 0
	if r != nil {
		n = 1
		for p := r.Next(); p != r; p = p.next {
			n++
		}
	}
	return n
}

// Do calls function f on each element of the ring, in forward order.
// The behavior of Do is undefined if f changes *r.
func (r *ThingRing) Do(f func(Thing)) {
	if r != nil {
		f(r.Value)
		for p := r.Next(); p != r; p = p.next {
			f(p.Value)
		}
	}
}
