// Generated by: gen
// TypeWriter: slice
// Directive: +gen on Price

// See http://clipperhouse.github.io/gen for documentation

package main

import (
	"errors"
)

// PriceSlice is a slice of type Price. Use it where you would use []Price.
type PriceSlice []Price

// Max returns the maximum value of PriceSlice. In the case of multiple items being equally maximal, the first such element is returned. Returns error if no elements. See: http://clipperhouse.github.io/gen/#Max
func (rcv PriceSlice) Max() (result Price, err error) {
	l := len(rcv)
	if l == 0 {
		err = errors.New("cannot determine the Max of an empty slice")
		return
	}
	result = rcv[0]
	for _, v := range rcv {
		if v > result {
			result = v
		}
	}
	return
}
