// Generated by: gen
// TypeWriter: gen
// Directive: +gen on typewriter.Tag

// See http://clipperhouse.github.io/gen for documentation

package typewriter

// Tags is a slice of type Tag. Use it where you would use []Tag.
type Tags []Tag

// Where returns a new Tags slice whose elements return true for func. See: http://clipperhouse.github.io/gen/#Where
func (rcv Tags) Where(fn func(Tag) bool) (result Tags) {
	for _, v := range rcv {
		if fn(v) {
			result = append(result, v)
		}
	}
	return result
}
